tests/common.py
tests/test_conversions.py
tests/test_counterfactualexplainer.py
tests/test_datautils.py
tests/test_limeexplainer.py
trustyai/__init__.py
trustyai/explainers.py
trustyai/model/__init__.py
trustyai/utils/DataUtils.py
trustyai/utils/__init__.py

https://github.com/trustyai-python/module/issues/10
- Added new Python/Java list converter
- Remove all `toJList` explicit dependencies
- Fix implicit converters names
- Added unit tests for conversions

Remove java.util.List explicit dependencies

---

tests/test_conversions.py
tests/test_counterfactualexplainer.py
trustyai/local/counterfactual.py
trustyai/model/domain.py

Closes https://github.com/trustyai-python/module/issues/32
- Feature domains can be create from `Tuple` of `int`, `float` or `str` and `List` of `str`
- `None` is interpreted as `EmptyFeatureDomain`
- `CounterfactualPrediction` accepts lists of the above (no need to create Java object directly)

Add ability to create FeatureDomains from native Python collections

---

tests/test_conversions.py
tests/test_counterfactualexplainer.py
tests/test_limeexplainer.py
tests/test_model.py
trustyai/model/__init__.py

Replace trustyai factory methods with type inference. Closes https://github.com/trustyai-python/module/issues/19

Replace TrustyAI factory methods with type inference

---

.github/workflows/workflow.yml
setup.py
tests/common.py
trustyai/__init__.py

This PR adds a post-install script which:
-  fetches the Java dependencies on `pip install`
- Installs them on `site-packages`
These JARs will be available in `virtualenvs` too.
The JARs fetched will be for a certain Kogito version which will be bumped when needed.
The JARs will be considered the "default" ones and the module can be initialised with
```python
import trustyai
trustyai.init()
```
If custom JARs need to used, the default ones can be overridden with
```python
import trustyai
trustyai.init(path=[ # list of paths to my JARs ]) 
```

Add post-install command to get Java dependencies

---

tests/test_shap.py
trustyai/explainers.py

This adds the visualize_as_dataframe and visualize_as_candlestick_plot functions from the example notebook into SHAP. SHAP now outputs a SHAPResults object, which is a wrapper of the Java ShapResults object.

FAI-759: Added SHAP visualization functions from the example notebook

---

README.md
setup.py
tests/test_counterfactualexplainer.py
tests/test_shap.py
trustyai/explainers.py
trustyai/utils/_visualisation.py

[FAI-762](https://issues.redhat.com/browse/FAI-762):
Common API for the visualisation methods.
- Abstract class for visualiser's common code and API
- SHAP, LIME and CF support `as_dataframe` method
- LIME and CF support `.plot()` method
- SHAP supports `candlestick_plot()` (future plots under `{waterfall, candlestick, ...}_plot()`
- Basic support for styles using pre-defined dict keys

[FAI-762] Standardise visualisation API across explainers

---

setup.py
trustyai/__init__.py

https://issues.redhat.com/browse/FAI-806
When trying to build the module in a virtualenv the site.getsitepackages() function can fail due to some strange virtualenv bug: https://github.com/pypa/virtualenv/issues/737, meaning ReadTheDocs can't build trustyai. This introduces a possible workaround using distutils.

FAI-806: Added distutils workaround to sitepackages virtualenv bug

---

tests/general/test_shap.py
trustyai/explainers.py

[FAI-816](https://issues.redhat.com/browse/FAI-816)
Adds a a bandaid type check to ensure the regardless of the Java library version the Python bindings `ShapResults.get_saliencies()` always outputs a `Dict[output_name, Saliency]`

FAI-816: Fixed incorrect ShapResults.get_saliency output type

---

trustyai/explainers.py

[FAI-802](https://issues.redhat.com/browse/FAI-802)
The SHAPExplainer had an unused "perturbation" argument, this is now removed.

FAI-802: Removed unused perturbation argument from SHAP explainer

---

trustyai/explainers.py

[FAI-824](https://issues.redhat.com/browse/FAI-824)
ShapResults.get_saliencies() checked for Python dicts, not Java maps, and therefore could not convert correctly the saliencies maps produced by the latest version of exp-core

FAI-824: Fixed ShapResults.get_saliencies() incorrectly parsing java maps

---

.github/workflows/publish.yml

The PyPi upload endpoint can be changed from the test site (`test.pypi.org`) to the live one (`pypi.org`).

FAI-845: Change PyPi upload endpoint from test to live

---

src/trustyai/explainers.py
src/trustyai/model/__init__.py

Python bindings counterparts for the `SaliencyResults` unification of https://github.com/trustyai-explainability/trustyai-explainability/pull/28

FAI-853: Python bindings for unified results

---

src/trustyai/model/__init__.py
tests/general/test_conversions.py

Creating categorical features with a string backing works as expected, but not with integer backings.
This causes errors when using transformers (e.g. `OrdinalEncoders`).

FAI-852: Fix Python conversion for categorical features with integer backing

---

.github/actions/build-arrow-converter/action.yml
.github/actions/build-core/action.yml
.github/workflows/workflow.yml

https://issues.redhat.com/browse/FAI-860
This PR improves CI:
- Tests of `trusty-ai-arrow` were disabled
- Shade jar for python binding was not building `trustyai-explainability` root modules (so it was just fetching that file from maven repositories)
- Minor improvement in Java/Maven version configuration

[FAI-860] Improve CI: enable test for Arrow module + make Expl-core build more reliable + minor improvements

---

src/trustyai/explainers.py

`normalize_weights` param of `LimeExplainer` should be set to `False` as in the java implementation.

set normalize_weights to False in LimeExplainer as in Java impl

---

pyproject.toml
src/trustyai/explainers/counterfactuals.py
src/trustyai/explainers/explanation_results.py
src/trustyai/explainers/lime.py
src/trustyai/explainers/shap.py
tests/general/test_counterfactualexplainer.py
tests/general/test_limeexplainer.py
tests/general/test_shap.py

BLocking behavior can be restored by passing `pytest -m block_plots`

FAI-893: Make test plots non-blocking by default

---

src/trustyai/utils/data_conversions.py
tests/general/test_conversions.py

The following can now be accepted as inputs/outputs:
- single values (i.e, one int, float, or np.number)
- lists of the above

FAI-901: Increased input/ouput conversion flexibility

---

src/trustyai/metrics/fairness/group.py

Allow `data_conversion` inputs to be used to select favorable outcomes in group fairness metrics.

FAI-911: Improve API to declare selections in Python fairness

---

src/trustyai/explainers/counterfactuals.py
src/trustyai/explainers/lime.py
src/trustyai/explainers/shap.py
src/trustyai/model/__init__.py
src/trustyai/utils/data_conversions.py
tests/general/test_counterfactualexplainer.py
tests/general/test_limeexplainer.py
tests/general/test_shap.py

Can now specify feature_name and output_names to models
For non-pandas inputs/outputs, the passed feature_names and output_names will be used in PredictionInputs/Outputs
For pandas inputs/outputs, the passed feature_names and output_names are ignored

FAI-825: Add feature and output name specification to models

---

CHANGELOG.md
cliff.toml

Automation provided by [git-cliff](https://github.com/orhun/git-cliff).
Ideally commits should follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification, but it's configured in a way that `FAI-XYZ: $message` (as typically used) is also accepted.

Add Git changelog automation

---

pyproject.toml
src/trustyai/model/__init__.py
tests/general/test_model.py

If we log and capture error messages from within the `predict_fun` we can display them before the JVM crashes, making debugging a whole lot easier.
Before:
After:

FAI-917: Add error message capturing within Python models

---

src/trustyai/explainers/counterfactuals.py
src/trustyai/model/__init__.py
tests/general/test_counterfactualexplainer.py
tests/general/test_model.py

[FAI-926](https://issues.redhat.com/browse/FAI-926)
This PR adds programmable goal criteria to the Python counterfactuals.
Goal criteria allow to pass arbitrarily complex functions as a goal (using the CF proposal predictions as inputs) for scenarios where a static goal might not be sufficient.
The criteria can be any Python function and may take either Pandas dataframes or Numpy arrays as inputs and must return a tuple consisting of distance and score.
This PR also abstracts some functionality previously on the `Model` wrapper class to a more generic `CallableWrapper`, since the goal criteria shares some common functionality with `Model`.

FAI-926: Implement custom counterfactual goal criteria

---

src/trustyai/initializer.py

Java logging in Python TrustyAI can be noisy, especially in counterfactuals where the log level is `warn` and within Jupyter notebooks.
This PR reduces the Java logging level to `error` (only when used from Python).

RHODS-7947: Reduce logging level of exp-core in Python TrustyAI

---

src/trustyai/utils/tyrus.py

Tyrus's input/output conversion currently breaks for numpy inputs, returning a null-pointer error. Imputing feature and output names should fix this issue.

fix: Fixed null pointer error for Numpy inputs to Tyrus

---

src/trustyai/utils/tyrus.py

Bokeh 3.0.x upgrade changed how bokeh's gridding and dynamic resizing works, this PR fixes the gridding+dynamic resizing functionality to (somewhat) return to how Tyrus was intended to look

fix: Fixed broken gridding after bokeh 3.0.x update

---

pyproject.toml

AIX360 0.3.0 is now released. This replaces the direct dependency with a PyPi dependency so that Python TrustyAI can be released.

Update direct dependency to released dependency

---

src/trustyai/metrics/distance.py
src/trustyai/metrics/language.py

Add Levenshtein distance to the metrics, along with distance matrix visualisation.

Add Levenshtein distance

---

docs/tutorial.rst

I believe I detected 2 typos:
- name of argument
- missing comma

fix typos in tutorial.rst

---

.github/workflows/workflow.yml
pyproject.toml
src/trustyai/utils/api/api.py
src/trustyai/utils/extras/metrics_service.py
tests/extras/test_metrics_service.py

addresses [RHOAIENG-3245](https://issues.redhat.com/browse/RHOAIENG-3245) by making adding the following methods:
* converts json files to pandas dfs and vice versa
* uploads data to service and/or model
* get metric request with the option to schedule for reoccurring intervals
* retrieves metric data from prometheus for specific time interval
demo nb to follow shortly

RHOAIENG-3245: add methods to execute and return queries from trustyai service

---

src/trustyai/utils/extras/metrics_service.py

this pr address #204 by making the following changes:
* adds method to visualize a specified metric wrt time
* updates `get_metric_data` to the correct version
* edit of `True` to `self.verify` in `label_data_fields`

# issue 204: add plot method and other minor edits

---

pyproject.toml
tests/general/test_conversions.py

Required for compatibility with ray and datasets on workbenches.

RHOAIENG-12556: Update PyArrow to 17.0.0

---

src/trustyai/language/detoxify/tmarco.py

This PR makes the following changes to `load_models` method:
- Adds functionality to load local models
- Adds functionality to load HF models

RHOAIENG-11952: Add ability to load local and HF models
