trustyai-explainability/trustyai-explainability-python

- tests/test_counterfactualexplainer.py
- trustyai/explainers.py
Closes https://github.com/trustyai-python/module/issues/26
Counterfactual configuration moved to inside the explainer
> Move CF config to explainer

- tests/test_counterfactualexplainer.py
- trustyai/model/__init__.py
Closes https://github.com/trustyai-python/module/issues/28
Add complimentary implicit class for `Output`
> Add implicit methods to Output

- tests/test_counterfactualexplainer.py
- trustyai/__init__.py
- trustyai/local/counterfactual.py
- trustyai/model/__init__.py
- Add helper methods with default values
- Refactor converters
- Simplify counterfactual tests
> Add helper methods and refactor converters

- tests/test_datautils.py
- tests/test_limeexplainer.py
- trustyai/explainers.py
- trustyai/local/counterfactual.py
- trustyai/model/__init__.py
- Add helper method to create SimplePrediction
- Move LIME config inside explainer
> Simplify LIME invocation

- tests/test_limeexplainer.py
- trustyai/model/__init__.py
Closes https://github.com/trustyai-python/module/issues/17
> Add implicit PredictionProvider method to remove async call

- README.md
- tests/common.py
- tests/test_counterfactualexplainer.py
- tests/test_limeexplainer.py
- tests/test_model.py
- trustyai/explainers.py
- trustyai/model/__init__.py
Closes https://github.com/trustyai-python/module/issues/10
- Update Python test model
- Test counterfactuals with Python model
- Add unit test for Model provider
- Simplify model provider async mechanism
- Update README.md
> Simplify model provider mechanism

- tests/test_counterfactualexplainer.py
- trustyai/local/counterfactual.py
Closes https://github.com/trustyai-python/module/issues/31
Add default constraints to counterfactuals.
> Add default constraints to counterfactuals

- tests/test_limeexplainer.py
- tests/test_shap.py
- trustyai/explainers.py
Working basic support for the SHAP kernel explainer.
> Add SHAP support

- MANIFEST.in
- README.md
- setup.py
Adding `arrow-converter` explicitly for `sdist` compatibility.
> Release fix 0.2.1

- tests/test_dataset.py
- trustyai/model/__init__.py
Support the creation of Datasets directly from Pandas dataframes.
> [FAI-781] Support creating Datasets directly from Pandas dataframes

- README.md
> FAI-797b: Include doc link in README

- tests/general/test_shap.py
- trustyai/explainers.py
https://issues.redhat.com/browse/FAI-800
Quick fix to the bug in ShapResults where it would only return the first dataframe in the `SHAPResults.as_dataframe` or `as_html` calls
> FAI-800: Fixed SHAP results only returning first df

- trustyai/explainers.py
[FAI-826](https://issues.redhat.com/browse/FAI-826)
SHAP was accessing fnulls using the old lookup method, compatibility with the newest version of exp-core has been added
> FAI-826: Fixed SHAP not accessing new fnull locations correctly

- setup.py
> Release 0.2.5

- tests/general/test_counterfactualexplainer.py
- tests/general/test_limeexplainer.py
- tests/general/test_model.py
- tests/general/test_shap.py
- tests/general/universal.py
- trustyai/explainers.py
- trustyai/model/__init__.py
https://issues.redhat.com/browse/FAI-834
> FAI-834: Fixed Model not assigning output names consistently

- src/trustyai/initializer.py
https://arrow.apache.org/docs/java/install.html#java-compatibility
> FAI-867: Add Java 9+ Arrow compatibility flags

- pyproject.toml
- requirements.txt
Update JPype version from 1.3.0 to 1.4.1.
> FAI-878: Update JPype version

- scripts/local.sh
Added a script for installing the Python bindings using a locally built TrustyAI java library.
> script for installing using a locally built TrustyAI java lib

- src/trustyai/explainers/counterfactuals.py
- src/trustyai/explainers/explanation_results.py
- src/trustyai/explainers/lime.py
- src/trustyai/explainers/shap.py
- src/trustyai/model/__init__.py
- src/trustyai/utils/_visualisation.py
- src/trustyai/utils/tyrus.py
- tests/general/test_limeexplainer.py
- tests/general/test_shap.py
Created a unified abstract class for all Explanation results, and a subclass for SaliencyResults. This merges the syntax and behavior of LIME + SHAPs plotting functions
> FAI-887: Generalize ExplanationResults

- src/trustyai/model/__init__.py
- src/trustyai/utils/text.py
- tests/general/test_conversions.py
Add the full text feature builder from Java TrustyAI.
This is mainly to increase test coverage and parity with explainabilty-core.
> FAI-898: Add full text feature builder

- src/trustyai/explainers/lime.py
See https://issues.redhat.com/browse/FAI-922.
> FAI-922 - expose LimeConfig options in LimeExplainer

- CHANGELOG.md
- README.md
- pyproject.toml
- src/trustyai/version.py
> Release 0.2.8

- CHANGELOG.md
- README.md
- pyproject.toml
- src/trustyai/version.py
> Release 0.2.9

- CHANGELOG.md
- README.md
- pyproject.toml
- src/trustyai/version.py
> Release 0.2.10

- CHANGELOG.md
- README.md
- pyproject.toml
- src/trustyai/version.py
> Release 0.2.11

- CHANGELOG.md
- README.md
- pyproject.toml
- src/trustyai/version.py
> Release 0.2.12

- pyproject.toml
- requirements.txt
> Upgrade pyarrow dependency

- .github/workflows/workflow.yml
- pyproject.toml
- src/trustyai/explainers/extras/tsice.py
- tests/extras/tsice/test_tsice.py
This PR:
- Adds support for the AIX360 TSICE explainer within TrustyAI
- Adds unit test for the new explainer
- Updates CI to include `[extras]` dependencies
> Initial support for external algorithms

- src/trustyai/explainers/extras/tsice.py
- src/trustyai/utils/extras/timeseries.py
- tests/extras/tsice/test_tsice.py
Add `plot_forecast` and `plot_impact` to TSICE explanations.
TSICE explanations now a sub-class of
> Support TSICE explanations as plots

- src/trustyai/metrics/language.py
- tests/general/test_metrics_language.py
Change WER signature to match new exp-core signature.
> Change WER signature

- src/trustyai/language/detoxify/tmarco.py
Enables GPU usage for TMaRCo during expert model training and inference
> Enable GPU usage for TMaRCo

- .github/workflows/workflow.yml
- pyproject.toml
- src/trustyai/language/detoxify/tmarco.py
See [RHOAIENG-12605](https://issues.redhat.com/browse/RHOAIENG-12605).
Update Jpype to 1.5.0, as it adds improved support for Python 3.11.
> RHOAIENG-12605: Update JPype to 1.5.0

- .github/workflows/security.yaml
> Add Trivy scanning
